const firstName = document.getElementById('first-name')
const lastName = document.getElementById('last-name')
const email = document.getElementById('email')
const country = document.getElementById('country')
const zip = document.getElementById('zip')
const password = document.getElementById('password')
const passwordConfirm = document.getElementById('password-confirm')